spring:
  application:
    name: WalletAPI
  datasource:
    url: jdbc:h2:mem:dbtest
    driver-class-name: org.h2.Driver
    username: in2admin
    password: in2pass
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    properties:
      jakarta.persistence.sharedCache.mode: UNSPECIFIED
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true

server:
  port: 8082

in2:
  openapi:
    local-url: http://localhost:8082
    dev-url: http://localhost:8082 # TODO - Change

app:
  url:
    api: http://localhost:8082 # TODO - Change
    verifiable-credential-service-baseurl: http://localhost:8083/api/credentials
    siop-service-baseurl: http://localhost:8083/api/siop

# Spring Management Configuration - Actuator
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info, loggers, metrics
      base-path: /
      path-mapping:
        health: health
        info: info
        loggers: loggers
        metrics: metrics
  endpoint:
    health:
      enabled: true
      show-details: always
    info:
      enabled: true
    loggers:
      enabled: true
    metrics:
      enabled: true



