spring:
  application:
    name: WalletAPI
  datasource:
    url: jdbc:h2:mem:dbtest
    driver-class-name: org.h2.Driver
    username: in2admin
    password: in2pass
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    properties:
      jakarta.persistence.sharedCache.mode: UNSPECIFIED
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
  security:
    user:
      name: in2test
      password: in2pass

server:
  port: 8084

in2:
  openapi:
    local-url: http://localhost:8084
    dev-url: http://localhost:8084 # TODO - Change

app:
  url:
    api: http://localhost:8084 # TODO - Change

